networks:
  virt_container_net:
    driver: bridge
    enable_ipv6: true

services:
  keycloak_web:
    image: keycloak/keycloak:latest
    container_name: kc-web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}

      KEYCLOAK_ADMIN: ${KC_DB_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_DB_PASSWORD}

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 1314
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_LOG_LEVEL: debug

      KC_METRICS_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
      KC_PROXY: edge
      KC_PROXY_HEADERS: forwarded
      KC_HTTP_RELATIVE_PATH: "/auth"
    command: start-dev
    depends_on:
      - postgres
    ports:
      - '7070:1314'
    networks:
      - virt_container_net
  ######################################################
  postgres:
    image: postgres:15
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    networks:
      - virt_container_net
  ######################################################
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    # image: panderu/study-buddies-backend:latest
    container_name: spring-backend
    ports:
      - "1516:8080"
    depends_on:
      - keycloak_web
    networks:
      - virt_container_net
  ######################################################
  nginx:
    image: nginx:latest
    network_mode: host
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - spring
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
