server:
    port: 8080
spring:
    application:
        name: server
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/studbud
        username: spring
        password: SuperSecretPassword
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                ddl-auto: update

springdoc:
    swagger-ui.path: /api-docs
